spring:
  application:
    name: mailing-backend

  datasource:
    url: jdbc:h2:file:./data/mailing;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME:6ad9be5e7ef0b7}
    password: ${MAILTRAP_PASSWORD:90c4b49af30f47}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080
