spring:
  application:
    name: mailing-backend

  datasource:
    url: jdbc:h2:file:./data/mailing;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail.username}
    password: ${gmail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true # 추가해주면 보안 연결이 더 확실해집니다.

gemini:
  api:
    key: ${gemini.api.key}

newsletter:
  recipient: blaze121304@gmail.com

server:
  port: 10004
